#+title: MAT2250 mandatory assignment
#+author: Thomas Heartman
#+date: {{{time(%Y-%m-%d)}}}
#+options: toc:nil
#+latex_class: uio-memoir
#+description: This is my description.

#+begin_problem
*Stirling numbers of the 2nd kind and generating functions*

1. Use a counting argument to show that  the Stirling numbers of the second kind satisfy $S_{n, 2} = 2^{n-1} -1$ for $n\geq 1$ (recall  that $S_{0, k} = 0$). Express the generating function $$\mathcal{S}_2(z) = \sum_{n = 0}^\infty S_{n, 2} z^n$$ as a rational function.

   #+begin_answer
   First, let's show that the Stirling numbers of the second kind
   satisfy $S_{n, 2} = 2^{n-1} - 1$ for $n \ge 1$. We'll look at them in a
   few different ways: we'll look at the recurrence relation and
   explain why the counting is correct; we'll look at an inductive
   proof for why this is always $2^{n-1} -1$, and finally, we'll see a
   bijection to binary strings that we can use four counting.

   Let's start by analyzing the well-known recurrence relation for
   Stirling numbers of the second kind: $S_{n, k} = S_{n-1, k-1} + k S_{n-1,
   k}$. Let /X/ be an /n/-set and /a/ \in /X/. Then the first summand is
   the number of set partitions where /a/ is the only element of its
   partition. That is, /a/ \in some partition /A/, $|A| = 1$. This
   leaves us to partition the remaining $n - 1$ elements into $k-1$
   partitions. For the second summand, assume that /a/ is not the only
   member of its partition. That means, we can remove /a/, and still
   have /k/ non-empty partitions, yielding $S_{n-1, k}$. Because
   inserting /a/ into any of these /k/ partitions would yield a
   different configuration, we have to multiply $S_{n-1,k}$ by /k/ to get
   all possible configurations.

   In our case, however, we're only dealing with partitioning a set
   into 2, so the recurrence relation takes on the simpler form $S_{ n,2
   } = S_{n-1,1} + 2S_{n-1, 2}$. This further simplifies to $S_{n,2} = 1 +
   2S_{n-1, 2}$, because $S_{n, 1} = 1$ for all $n \ge 1$. We can test that
   the Stirling numbers of the second kind satisfy the equation $S_{n,2}
   = 2^{n-1} - 1$ for $n = 1$ and $n=2$. To show that it holds for
   arbitrary /n/, we'll use induction.

   Assume that $S_{n,2} = 2^{n-1} - 1$ holds for some value of $n$. We'll
   show that in that case, it also holds for $n+1$. If we shift the
   equation's indices down by one, we get that $S_{n-1, 2} = 2^{n-2} - 1$.
   We can plug that into the equation and get:

   \begin{align*}
   S_{n,2} & = S_{n-1,1} + 2S_{n-1, 2}\\
   & = 1 + 2(2^{n-2} - 1) \\
   & = 1 + 2^{n-1} - 2 \\
   & = 2^{n-1} - 1
   \end{align*}

   Finally, let's look at a bijection to the set of binary strings of
   length $n$ that start with a $0$. We'll let each character of
   the string represent a single element of the set, and its value is
   whether it's in set $A$ or $B$. For simplicity's sake, we'll place
   all elements represented by a 0 in $A$, and all characters
   represented by a 1 in $B$.

   We know that there are $2^n$ possible permutations of a binary string of
   length $n$. However, because two sets $A$ and $B$ are equal if they
   contain the same elements, half of these $2^n$ configurations are
   indistinguishable from the other half (their /flipped/
   counterparts, e.g. $010$ and $101$). Assuming our set has a partial
   order, we can fix the first element (our 0), and look at the $2^{n-1}$
   remaining possible permutations. Of those, there is only a single
   one that is invalid: the permutation of all zeroes (meaning that
   every element is in the same partition).
   #+end_answer

2. Use the recurrence relation $S_{n, k} = S_{n-1, k-1} + k S_{n-1, k}$  and the formula found above for $\mathcal{S}_2(z)$ to prove that $$\mathcal{S}_3(z) := \sum_{n = 0}^\infty S_{n, 3} z^n =  \frac{z^3}{(1-z)(1-2z)(1-3z)}.$$

3. Use a partial fraction decomposition of the generating function $\mathcal{S}_3(z)$ to obtain a closed formula for $S_{n, 3}$.
#+end_problem

#+begin_problem
*Graphs from sets*

1. Recall the hypercube graph is $Q_n = (V(Q_n), E(Q_n))$ where $$V(Q_n) = \{ u_1 \dots u_n \ | \ u_i = 0, 1 \}$$ and $$E(Q_n) = \{ uv \ | \ u, v \text{ binary words differing in exactly one letter} \}.$$ What are the sizes of $V(Q_n)$ and $E(Q_n)$?

2. Assuming all edges have weight 1, what is the distance in $Q_n$ from $00\dots00$ to $u = u_1u_2 \dots u_n$ ? What is the distance in $Q_n$ between two arbitrary words $u$ and $v$?

3. Orient the edge $k = uv$  of $Q_n$ so that  $u = k^-$ and $v = k^+$ if the word $v$ contains more $1$'s  than $u$. Prove that the orientation is acyclic. Which word corresponds to a sink and which word is a source?

#+end_problem

#+begin_problem
*Greedy algorithms*

Consider the graph $G$ with weight function prescribed along its edges:


 \begin{center}\newcommand\size{3}% distance of nodes from center

\begin{tikzpicture}

\draw [thick,black] (0,0)-- (18:\size)  node [above, midway] {3};
\draw [thick,black] (0,0)-- (90:\size)  node [left, midway] {2};
\draw [thick,black] (0,0)-- (162:\size)  node [above, midway] {1};
\draw [thick,black] (0,0)-- (234:\size)  node [above, midway] {1};
\draw [thick,black] (0,0)-- (306:\size)  node [above, midway] {3};


  \draw[thick,black]  (18:\size)--(90:\size) node [above, midway] {4};
    \draw[thick,black]  (90:\size)--(162:\size) node [above, midway] {2};
    \draw[thick,black]  (162:\size)--(234:\size) node [left, midway] {3};
    \draw[thick,black]  (234:\size)--(306:\size) node [above, midway] {2};
     \draw[thick,black]  (18:\size)--(306:\size) node [right, midway] {4};

      \node[black,circle,draw, fill= white, inner sep=2pt] at (18:\size){$u_1$};
  \node[black,circle,draw, fill= white, inner sep=2pt] at (90:\size){$u_0$};
   \node[black,circle,draw, fill= white, inner sep=2pt]at (162:\size){$u_4$};
      \node[black,circle,draw, fill= white, inner sep=2pt] at (234:\size){$u_3$};
       \node[black,circle,draw, fill= white, inner sep=2pt] at (306:\size){$u_2$};
         \node[black,circle,draw, fill= white, inner sep=2pt] at (0:0){$u_5$};
 \end{tikzpicture}
 \end{center}

1. Run Dijkstra's algorithm from starting vertex  $u_0$ to find a tree containing all minimal weight paths from $u_0$ with the prescribed weight function. Write down which edge and vertex is selected at each step of the algorithm.

   What is the length of the shortest weighted path in $G$ from $u_0$ to $u_3$?

2. Run Kruskal's algorithm to find a minimal spanning tree of $G$ for the given weight function.

   What is the weight of a  minimal spanning tree in $G$? Is there a unique minimal spanning tree in $G$ with this weight function?

3. Show that if the greedy algorithm on matroids from Theorem 7.13  can select two distinct bases  $B_1$ and  $B_2$ of minimal weight, then there must exist $s_1 \in B_1$ and $s_2 \in B_2$ such that $w(s_1) = w(s_2)$. Conclude that if the weight function $w : S \to \mathbb{R}$  is an injective  map then the greedy algorithm selects a unique minimal basis of a matroid.

   Find an example of a weighted graph which shows that the converse to the above statement is false. Namely that there is a graph $G$ with weight function  $w : E \to \mathbb{R}$  which is not injective but the greedy algorithm still selects a unique minimal spanning tree.

#+end_problem

#+begin_problem
*Matchings*

1. Consider the bipartite graph:
   \begin{center}
   \begin{tikzpicture}
      \graph[nodes={draw, circle}, radius=.25cm,
              branch down=1 cm,       grow right sep=4cm]
              {subgraph I_nm [V={a, b, c, d}, W={1,...,4}];
     a -- { 2};
     b -- { 3, 4 };
     c -- { 1,2 };
     d -- { 1,2}
   };
   \end{tikzpicture}
   \end{center}

   Determine the matching number of $G$ and find a maximal matching.

2. The hypercube graph  $Q_n$ is bipartite, with the two disjoint vertex sets being determined by the binary  words containing an even or odd number of $1$'s. The matching number of $Q_n$ is $2^{n-1}$. Describe a maximal matching of $Q_n$.

3. Let  $S$ be the set of binary words of length $n$ with $k$ number of $1's$ and let $T$ be the set of binary words of length $n$ with $k+1$ number of  $1$'s. Let $E = \{st \ | \ s, t \text{ differ in exactly one letter}  \}$ and set  $H = (S \cup T, E)$ (notice $H$ is an induced subgraph of $Q_n$).
   - What are  the degrees in $H$  of vertices in $S$ and vertices in $T$?

   - Prove that for any subset $A$ of $S$  we have $(k+1) |N(A)|  \geq (n-k)  |A|$.

     Hint: consider the set of edges incident to $A$ and the set of edges incident to $N(A)$.

   - Use Hall's matching condition to conclude that $m(H) = |S|$ for  $k <n/2$.

   Conclude that there exists an injective map $f$ from the subsets of size $k$ of $\{1, \dots, n\}$ to the subsets of size $k+1$ of $\{1, \dots ,n\}$ satisfying $I \subset f(I)$ for $k < n/2$.
#+end_problem
